version: '3.3'
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  frontend:
    image: bonjourgod/diplom-frontend:v.1
    volumes:
      - ../frontend/:/app/result_build/

  backend:
    image: bonjourgod/diplom-backend:v.1
    restart: always
    volumes:
      - static_dir:/app/static/
      - media_dir:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_dir:/var/html/static/
      - media_dir:/var/html/media/

    depends_on:
      - backend
      - frontend

volumes:
  static_dir:
  media_dir:
  postgres_data: