# Generated by Django 2.2.19 on 2023-06-17 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20230617_2146'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='amountimgredientsinrecipe',
            unique_together={('recipe', 'ingredient')},
        ),
    ]
