# Generated by Django 2.2.19 on 2023-06-15 20:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0003_auto_20230615_1741'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FavouriteRecipe',
            new_name='FavoriteRecipe',
        ),
    ]
